apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kibana.172.16.2.10.nip.io 
    http:
      paths:
      - backend:
          serviceName: kibana-kibana
          servicePort: 5601
  tls:
   - secretName: traefik-ui-tls-cert